configs:
  proxy.conf:
    file: ./configs/proxy/default.conf
  web.conf:
    file: ./configs/web/default.conf
networks:
  frontend:
  backend:
services:
  app:
    image:              zwilson/blog
    build:              https://github.com/zazazack/blog.git
    environment:
      - PYTHONUBUFFERED=1
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - FLASK_APP=blog
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./blog:/usr/src/app/blog
      - ./tests:/usr/src/app/tests
      - ./setup.py:/usr/src/app/setup.py
      - ./setup.cfg:/usr/src/app/setup.cfg:ro
      - ./requirements.txt:/usr/src/app/requirements.txt
    command:            waitress-serve --call blog:create_app
  proxy:
    image:              nginx:alpine
    configs:
      - source: proxy.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    ports:
      - 8000:8000
  web:
    image:              nginx:alpine
      configs:
        - source: web.conf
          target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - 80:80
version:                "3.7"
